[[plugins]]
repo = 'beckorz/previm'
on_ft = ['markdown', 'rst', 'mkd', 'textile']
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'

#[[plugins]]
#repo = 'previm/previm'
## on_ft = ['markdown', 'rst', 'mkd']
#on_cmd = 'PrevimOpen'
#depends = 'open-browser.vim'

[[plugins]]
repo = 'andymass/vim-matchup'
on_ft = ['python']

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'yukimemi/futago.vim'
on_cmd = ['FutagoStartChat', 'FutagoHistory', 'FutagoGitCommit']
depends = 'denops.vim'
