# @see: [textlintで表記ゆれチェックルール集を一部無視する設定 | DevelopersIO](https://dev.classmethod.jp/articles/eetann-ignore-textlint-rule-prh/)
# npx prh --rules %userprofile%/node_modules/prh/prh-rules/media/WEB+DB_PRESS.yml --rules-yaml
# npx prh --rules %userprofile%/node_modules/prh/prh-rules/media/techbooster.yml --rules-yaml

version: 1
imports:
  - path: ./node_modules/prh/prh-rules/media/techbooster.yml
    disableImports: true
    ignoreRules:
      - expected: （$1）
